name: Building CV
on:
  push:
    branches:
      - main
jobs:
    Building:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning repo
          uses: actions/checkout@v3
        - name: Show folder files
          run: ls
        - name: Building latex in Docker
          uses: ./.github/actions/build
      
        
