name: Building CV
on:
  push:
    branches:
      - main
jobs:
    Building:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning repo
          uses: actions/checkout@v3
        - name: Show folder files
          run: ls
        - name: Show current path
          run: pwd
        - name: Building latex in Docker
          uses: ./.github/actions/build
        - name: Change folder
          run: cd source
        - name: Browse files
          run: ls
      
        
