name: Building CV
on:
  push:
    branches:
      - main
    paths:
      - 'source/*'
      - 'Dockerfile'
      - '.github/**'
jobs:
    Building:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning repo
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Show folder files
          run: find . -maxdepth 2 ! -path "./.git/*"
        - name: Building latex in Docker
          uses: ./.github/actions/build
        - name: Browse files
          run: find . -maxdepth 2 ! -path "./.git/*"
        - name: Config bot to push result pdf
          env: 
            CI_COMMIT_MESSAGE: Push pdf
            CI_COMMIT_AUTHOR: Github actions CI
            BRANCH_NAME: result
          run: |
           git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
           git config --global user.email "username@users.noreply.github.com"
           git add -f source/cv.pdf
           git stash
           git checkout "${{ env.BRANCH_NAME }}"
           rm source/cv.pdf 2>/dev/null
           git add source/cv.pdf
           git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
           git stash pop
           git commit --amend -m "${{ env.CI_COMMIT_MESSAGE }}"
           git push -f
          
          
            
      
        
